AMQP_URI: 'pyamqp://guest:guest@localhost'
rpc_exchange: 'nameko-rpc'
REDIS_URL: 'redis://localhost:6379/1'
DB_URIS: 
    user_service:Base: 
      "postgresql+psycopg2://postgres:secret@localhost/ 
      users?client_encoding=utf8"
