version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.5-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - 'rabbitmq_data:/data'
volumes:
  rabbitmq_data:
    driver: local
